# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: 'mHM'
subtitle: 'The mesoscale Hydrologic Model'
name: "mHM Developers"
description: |- # this means to ignore newlines
  The mesoscale Hydrologic Model

github_username: mhm-ufz
minimal_mistakes_skin: dark
search: false
breadcrumbs: true
logo: /assets/images/mhm-logo_minimal.png

# Build settings
markdown: kramdown
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages
  - _guides

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

footer:
  links:
    - label: "UFZ"
      icon: "fas fa-graduation-cap"
      url: "https://www.ufz.de/mhm/"
    - label: "UFZ-GitLab"
      icon: "fab fa-fw fa-gitlab"
      url: "https://git.ufz.de/mhm/mhm"
    - label: "Discussions"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/mhm-ufz/mhm/discussions"

defaults:
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      classes: wide
      author_profile: false

  # _guides
  - scope:
      path: "_guides"
      type: pages
    values:
      sidebar:
        nav: guides
      layout: single
      classes: wide
      author_profile: false

atom_feed:
  hide: true
